### ISSUE TITLE
Drupal 9 support

### ISSUE THREAD

**Issue by didierdemaeyer** [openeuropa/oe_time_caching#6]
### Description

Add support for Drupal 9.

### Additional information

Upgrade Status report:
[single-export-oe_time_caching-2021-03-19T14_21_18+0100.txt](https://github.com/openeuropa/oe_time_caching/files/6171629/single-export-oe_time_caching-2021-03-19T14_21_18%2B0100.txt)

**Comment by brummbar** [comment]
Fixed in #8.
